//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4963
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bpf.Security.Common
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPassCredential", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Security.Common.FingerPrintCredential))]
    public partial class UserPassCredential : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Bpf.Security.Authentication.Common.Company companyField;
        
        private string passwordField;
        
        private string userNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Bpf.Security.Authentication.Common.Company company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FingerPrintCredential", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Common")]
    public partial class FingerPrintCredential : Bpf.Security.Common.UserPassCredential
    {
        
        private byte[] fingerPrintField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] fingerPrint
        {
            get
            {
                return this.fingerPrintField;
            }
            set
            {
                this.fingerPrintField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticatedToken", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Common.Exceptions.FunctionalExceptionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Common.Exceptions.FrameworkExceptionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Common.Exceptions.TechnicalExceptionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Security.Authentication.Common.Exceptions.AuthenticationExceptionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Security.Common.UserPassCredential))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Security.Common.SecurityData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Security.Common.FingerPrintCredential))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Security.Authentication.Common.Company))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Security.Authentication.Common.Privilege[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Security.Authentication.Common.Privilege))]
    public partial class AuthenticatedToken : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime creationDateField;
        
        private object idField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime creationDate
        {
            get
            {
                return this.creationDateField;
            }
            set
            {
                this.creationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityData", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Common")]
    public partial class SecurityData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Bpf.Security.Authentication.Common.Privilege[] PrivilegesField;
        
        private string[] RolesField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bpf.Security.Authentication.Common.Privilege[] Privileges
        {
            get
            {
                return this.PrivilegesField;
            }
            set
            {
                this.PrivilegesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
}
namespace Bpf.Security.Authentication.Common
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Authentication.Common")]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private long IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Privilege", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Authentication.Common")]
    public partial class Privilege : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string DescriptionField;
        
        private long IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
}
namespace Bpf.Common.Exceptions
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Security.Authentication.Common.Exceptions.AuthenticationExceptionInfo))]
    public partial class FunctionalExceptionInfo : Bpf.Common.Exceptions.FrameworkExceptionInfo
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FrameworkExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Common.Exceptions.TechnicalExceptionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Common.Exceptions.FunctionalExceptionInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Bpf.Security.Authentication.Common.Exceptions.AuthenticationExceptionInfo))]
    public partial class FrameworkExceptionInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private System.Collections.Generic.Dictionary<string, string> DataField;
        
        private string ExceptionFullTypeNameField;
        
        private string FriendlyMessageField;
        
        private Bpf.Common.Exceptions.FrameworkExceptionInfo InnerExceptionInfoField;
        
        private string StackTraceField;
        
        private string TechnicalMessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionFullTypeName
        {
            get
            {
                return this.ExceptionFullTypeNameField;
            }
            set
            {
                this.ExceptionFullTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyMessage
        {
            get
            {
                return this.FriendlyMessageField;
            }
            set
            {
                this.FriendlyMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Bpf.Common.Exceptions.FrameworkExceptionInfo InnerExceptionInfo
        {
            get
            {
                return this.InnerExceptionInfoField;
            }
            set
            {
                this.InnerExceptionInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnicalMessage
        {
            get
            {
                return this.TechnicalMessageField;
            }
            set
            {
                this.TechnicalMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TechnicalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    public partial class TechnicalExceptionInfo : Bpf.Common.Exceptions.FrameworkExceptionInfo
    {
    }
}
namespace Bpf.Security.Authentication.Common.Exceptions
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Authentication.Common.Except" +
        "ions")]
    public partial class AuthenticationExceptionInfo : Bpf.Common.Exceptions.FunctionalExceptionInfo
    {
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAuthenticationService")]
public interface IAuthenticationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LogInUserPass", ReplyAction="http://tempuri.org/IAuthenticationService/LogInUserPassResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Security.Authentication.Common.Exceptions.AuthenticationExceptionInfo), Action="http://tempuri.org/IAuthenticationService/LogInUserPassAuthenticationExceptionInf" +
        "oFault", Name="AuthenticationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Authentication.Common.Except" +
        "ions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.TechnicalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/LogInUserPassTechnicalExceptionInfoFaul" +
        "t", Name="TechnicalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FrameworkExceptionInfo), Action="http://tempuri.org/IAuthenticationService/LogInUserPassFrameworkExceptionInfoFaul" +
        "t", Name="FrameworkExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FunctionalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/LogInUserPassFunctionalExceptionInfoFau" +
        "lt", Name="FunctionalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    Bpf.Security.Common.AuthenticatedToken LogInUserPass(Bpf.Security.Common.UserPassCredential token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/FullAuthenticate", ReplyAction="http://tempuri.org/IAuthenticationService/FullAuthenticateResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.TechnicalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/FullAuthenticateTechnicalExceptionInfoF" +
        "ault", Name="TechnicalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Security.Authentication.Common.Exceptions.AuthenticationExceptionInfo), Action="http://tempuri.org/IAuthenticationService/FullAuthenticateAuthenticationException" +
        "InfoFault", Name="AuthenticationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Authentication.Common.Except" +
        "ions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FrameworkExceptionInfo), Action="http://tempuri.org/IAuthenticationService/FullAuthenticateFrameworkExceptionInfoF" +
        "ault", Name="FrameworkExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FunctionalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/FullAuthenticateFunctionalExceptionInfo" +
        "Fault", Name="FunctionalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    Bpf.Security.Common.AuthenticatedToken FullAuthenticate(Bpf.Security.Common.UserPassCredential token, ref Bpf.Security.Common.SecurityData data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LogInFingerPrint", ReplyAction="http://tempuri.org/IAuthenticationService/LogInFingerPrintResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.TechnicalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/LogInFingerPrintTechnicalExceptionInfoF" +
        "ault", Name="TechnicalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Security.Authentication.Common.Exceptions.AuthenticationExceptionInfo), Action="http://tempuri.org/IAuthenticationService/LogInFingerPrintAuthenticationException" +
        "InfoFault", Name="AuthenticationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Authentication.Common.Except" +
        "ions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FrameworkExceptionInfo), Action="http://tempuri.org/IAuthenticationService/LogInFingerPrintFrameworkExceptionInfoF" +
        "ault", Name="FrameworkExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FunctionalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/LogInFingerPrintFunctionalExceptionInfo" +
        "Fault", Name="FunctionalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    Bpf.Security.Common.AuthenticatedToken LogInFingerPrint(Bpf.Security.Common.FingerPrintCredential token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/AuthenticateUserPass", ReplyAction="http://tempuri.org/IAuthenticationService/AuthenticateUserPassResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.TechnicalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/AuthenticateUserPassTechnicalExceptionI" +
        "nfoFault", Name="TechnicalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Security.Authentication.Common.Exceptions.AuthenticationExceptionInfo), Action="http://tempuri.org/IAuthenticationService/AuthenticateUserPassAuthenticationExcep" +
        "tionInfoFault", Name="AuthenticationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Authentication.Common.Except" +
        "ions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FrameworkExceptionInfo), Action="http://tempuri.org/IAuthenticationService/AuthenticateUserPassFrameworkExceptionI" +
        "nfoFault", Name="FrameworkExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FunctionalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/AuthenticateUserPassFunctionalException" +
        "InfoFault", Name="FunctionalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    bool AuthenticateUserPass(Bpf.Security.Common.UserPassCredential token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/AuthenticateFingerPrint", ReplyAction="http://tempuri.org/IAuthenticationService/AuthenticateFingerPrintResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Security.Authentication.Common.Exceptions.AuthenticationExceptionInfo), Action="http://tempuri.org/IAuthenticationService/AuthenticateFingerPrintAuthenticationEx" +
        "ceptionInfoFault", Name="AuthenticationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Authentication.Common.Except" +
        "ions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.TechnicalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/AuthenticateFingerPrintTechnicalExcepti" +
        "onInfoFault", Name="TechnicalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FrameworkExceptionInfo), Action="http://tempuri.org/IAuthenticationService/AuthenticateFingerPrintFrameworkExcepti" +
        "onInfoFault", Name="FrameworkExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FunctionalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/AuthenticateFingerPrintFunctionalExcept" +
        "ionInfoFault", Name="FunctionalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    bool AuthenticateFingerPrint(Bpf.Security.Common.FingerPrintCredential token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/LogOut", ReplyAction="http://tempuri.org/IAuthenticationService/LogOutResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FunctionalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/LogOutFunctionalExceptionInfoFault", Name="FunctionalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.TechnicalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/LogOutTechnicalExceptionInfoFault", Name="TechnicalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    void LogOut(Bpf.Security.Common.AuthenticatedToken token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/Refresh", ReplyAction="http://tempuri.org/IAuthenticationService/RefreshResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.TechnicalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/RefreshTechnicalExceptionInfoFault", Name="TechnicalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FrameworkExceptionInfo), Action="http://tempuri.org/IAuthenticationService/RefreshFrameworkExceptionInfoFault", Name="FrameworkExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FunctionalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/RefreshFunctionalExceptionInfoFault", Name="FunctionalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Security.Authentication.Common.Exceptions.AuthenticationExceptionInfo), Action="http://tempuri.org/IAuthenticationService/RefreshAuthenticationExceptionInfoFault" +
        "", Name="AuthenticationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Authentication.Common.Except" +
        "ions")]
    void Refresh();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/GetPrivilegesForLoggedUser", ReplyAction="http://tempuri.org/IAuthenticationService/GetPrivilegesForLoggedUserResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Security.Authentication.Common.Exceptions.AuthenticationExceptionInfo), Action="http://tempuri.org/IAuthenticationService/GetPrivilegesForLoggedUserAuthenticatio" +
        "nExceptionInfoFault", Name="AuthenticationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Authentication.Common.Except" +
        "ions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FrameworkExceptionInfo), Action="http://tempuri.org/IAuthenticationService/GetPrivilegesForLoggedUserFrameworkExce" +
        "ptionInfoFault", Name="FrameworkExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FunctionalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/GetPrivilegesForLoggedUserFunctionalExc" +
        "eptionInfoFault", Name="FunctionalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.TechnicalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/GetPrivilegesForLoggedUserTechnicalExce" +
        "ptionInfoFault", Name="TechnicalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    Bpf.Security.Authentication.Common.Privilege[] GetPrivilegesForLoggedUser();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticationService/GetRolesAsStringForLoggedUser", ReplyAction="http://tempuri.org/IAuthenticationService/GetRolesAsStringForLoggedUserResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FrameworkExceptionInfo), Action="http://tempuri.org/IAuthenticationService/GetRolesAsStringForLoggedUserFrameworkE" +
        "xceptionInfoFault", Name="FrameworkExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Security.Authentication.Common.Exceptions.AuthenticationExceptionInfo), Action="http://tempuri.org/IAuthenticationService/GetRolesAsStringForLoggedUserAuthentica" +
        "tionExceptionInfoFault", Name="AuthenticationExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Security.Authentication.Common.Except" +
        "ions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.FunctionalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/GetRolesAsStringForLoggedUserFunctional" +
        "ExceptionInfoFault", Name="FunctionalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    [System.ServiceModel.FaultContractAttribute(typeof(Bpf.Common.Exceptions.TechnicalExceptionInfo), Action="http://tempuri.org/IAuthenticationService/GetRolesAsStringForLoggedUserTechnicalE" +
        "xceptionInfoFault", Name="TechnicalExceptionInfo", Namespace="http://schemas.datacontract.org/2004/07/Bpf.Common.Exceptions")]
    string[] GetRolesAsStringForLoggedUser();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IAuthenticationServiceChannel : IAuthenticationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class AuthenticationServiceClient : System.ServiceModel.ClientBase<IAuthenticationService>, IAuthenticationService
{
    
    public AuthenticationServiceClient()
    {
    }
    
    public AuthenticationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AuthenticationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AuthenticationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AuthenticationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Bpf.Security.Common.AuthenticatedToken LogInUserPass(Bpf.Security.Common.UserPassCredential token)
    {
        return base.Channel.LogInUserPass(token);
    }
    
    public Bpf.Security.Common.AuthenticatedToken FullAuthenticate(Bpf.Security.Common.UserPassCredential token, ref Bpf.Security.Common.SecurityData data)
    {
        return base.Channel.FullAuthenticate(token, ref data);
    }
    
    public Bpf.Security.Common.AuthenticatedToken LogInFingerPrint(Bpf.Security.Common.FingerPrintCredential token)
    {
        return base.Channel.LogInFingerPrint(token);
    }
    
    public bool AuthenticateUserPass(Bpf.Security.Common.UserPassCredential token)
    {
        return base.Channel.AuthenticateUserPass(token);
    }
    
    public bool AuthenticateFingerPrint(Bpf.Security.Common.FingerPrintCredential token)
    {
        return base.Channel.AuthenticateFingerPrint(token);
    }
    
    public void LogOut(Bpf.Security.Common.AuthenticatedToken token)
    {
        base.Channel.LogOut(token);
    }
    
    public void Refresh()
    {
        base.Channel.Refresh();
    }
    
    public Bpf.Security.Authentication.Common.Privilege[] GetPrivilegesForLoggedUser()
    {
        return base.Channel.GetPrivilegesForLoggedUser();
    }
    
    public string[] GetRolesAsStringForLoggedUser()
    {
        return base.Channel.GetRolesAsStringForLoggedUser();
    }
}
